require 'simplecov'
require 'telegram/bot'
require 'rspec'
require 'sequel'
SimpleCov.start

require_relative '../lib/actuadores_sobre_mensajes/acciones_estudiante/accion_mostrar_entregas'
require_relative '../lib/actuadores_sobre_mensajes/acciones_estudiante/solicitar_tutoria'
require_relative '../lib/actuadores_sobre_mensajes/acciones_estudiante/menu_tutorias'
require_relative '../lib/actuadores_sobre_mensajes/acciones_estudiante/menu_entregas'
require_relative '../lib/actuadores_sobre_mensajes/listar_dudas_resueltas.rb'
require_relative '../lib/actuadores_sobre_mensajes/listar_dudas.rb'
require_relative '../lib/actuadores_sobre_mensajes/listar_dudas_pendientes.rb'
require_relative '../lib/actuadores_sobre_mensajes/listar_mis_dudas.rb'
require_relative '../lib/actuadores_sobre_mensajes/menu_dudas.rb'
require_relative '../lib/actuadores_sobre_mensajes/acciones_profesor/establecer_tutorias.rb'
require_relative '../lib/actuadores_sobre_mensajes/acciones_profesor/accion_sobre_tutoria.rb'
require_relative '../lib/actuadores_sobre_mensajes/acciones_profesor/menu_tutorias_profesor.rb'
require_relative '../lib/actuadores_sobre_mensajes/acciones_profesor/menu_principal_profesor'
require_relative '../lib/actuadores_sobre_mensajes/accion.rb'
require_relative '../lib/actuadores_sobre_mensajes/menu'
require_relative '../lib/actuadores_sobre_mensajes/crear_duda.rb'

require_relative '../lib/contenedores_datos/duda'
require_relative '../lib/contenedores_datos/respuesta'
require_relative '../lib/contenedores_datos/tutoria'
require_relative '../lib/contenedores_datos/usuario_desconocido'
require_relative '../lib/contenedores_datos/curso'
require_relative '../lib/contenedores_datos/usuario'

